### ISSUE TITLE
Add Pillar Block data as mapping in Eth Client

### ISSUE THREAD

**Issue by VargaElod23** [Taraxa-project/bridge#51]
# Explanation

Similarly to the TaraClient we need the EthClient to abide by saving pillarBlocks by epoch too. 

```
mapping(uint256 => bytes32) public finalizedBridgeRoots;
```

@kstdl will add an epoch to the node's side for every pillar block and we need to save proofs according to the epoch.

## Todos

- [ ] Add a new `bytes32 epochRootKey;` to EthClient.
- [ ] Convert EthClient's `bytes32 bridgeRoot;` to a mapping.
- [ ] Make `function processBridgeRoot(uint256 block_number, bytes[] memory account_proof, bytes[] memory storage_proof)` process on epoch instead of block number.
- [x] On the TaraClient's side whenever the `finalizedBridgeRoots[blocks[i].block.period] = finalized.block.bridgeRoot;` finalizedBridgeRoots are updated, we need to store based on epoch, same with EthClient.
